# Generated by Django 4.0.4 on 2022-06-13 00:55

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Text', models.TextField(null=True)),
                ('Created_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Published_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('Author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='blog.post')),
            ],
        ),
    ]
